development:
  adapter: mysql2
  encoding: utf8
  database: passion2profit
  pool: 5
  username: aimanox
  password: hsjytvhggihgu/dl*37
  port: 3306
  timeout: 5000
  socket: /var/run/mysqld/mysqld.sock



production:
  adapter: mysql2
  encoding: unicode
  database: bokrana_prod
  pool: 5
  username: aimanox
  password: hsjytvhggihgu/dl*37
  port: 3306
  timeout: 5000
  host: localhost
