# encoding: utf-8
# Autogenerated by the db:seed:dump task
# Do not hesitate to tweak this to your needs

Admin.create!([
  { :username => "aimanman", :email => "aiman3700@gmail.com", :hashed_password => "f9020547954adbc82aab0d5f04a89bef9c10f226", :salt_password => "2247d27eb79edaf8bfdf54a51c54a30eabbdf9f8", :failed_login_num => 0, :last_login => "2013-11-17 07:26:46", :lock => false, :access_code => "Ccyk-p1H", :active => true, :reactivate_url => "JM-yCv9VXxIgYUeSOMfhGg1384673008", :created_at => "2012-12-01 14:54:05", :updated_at => "2013-11-17 07:27:03" }
])


